# Operaciones matemáticas con valores complejos

3.6

- Problema  
        
        Su código para interactuar con el último esquema de autenticación web ha encontrado una singularidad y su única solución es rodearla en el plano complejo. O tal vez solo necesita realizar algunos cálculos usando números complejos.    
        

- Solución
        
        Los números complejos se pueden especificar usando la función compleja (real, imag) o por números de punto flotante con un sufijo j.   
        
Por ejemplo:

In [2]:
a = complex(2, 4)
b = 3 - 5j

In [3]:
a

(2+4j)

In [4]:
b

(3-5j)

In [5]:
a.real

2.0

In [7]:
b.imag

-5.0

In [8]:
a.conjugate()

(2-4j)

In [9]:
a + b

(5-1j)

In [10]:
a * b

(26+2j)

In [11]:
a / b

(-0.4117647058823529+0.6470588235294118j)

In [12]:
abs(a)

4.47213595499958

Para realizar funciones adicionales de valores complejos, como senos, cosenos o raíces cuadradas, usa el módulo cmath:

In [13]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218173j)

In [14]:
cmath.cos(a)

(-11.36423470640106-24.814651485634183j)

In [15]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

La mayoría de los módulos relacionados con las matemáticas de Python son conscientes de valores complejos. Por ejemplo, si
usa numpy, es sencillo hacer matrices de valores complejos y realizar
operaciones sobre ellos:

In [16]:
import numpy as np

In [17]:
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [18]:
a + 2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [19]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [20]:
import math
math.sqrt(-1)

ValueError: math domain error

In [21]:
(-2)**(1/2)

(8.659560562354934e-17+1.4142135623730951j)

# Trabajar con Infinity y NaNs

3.7

- Problema
        
        Necesita crear o probar los valores de coma flotante de infinito, infinito negativo o NaN (no es un número).     
        
- Solución
        
        Python no tiene una sintaxis especial para representar estos valores especiales de punto flotante, pero se puede crear usando float ().  

Por ejemplo:

In [22]:
a = float('inf')
b = float('-inf')
c = float('nan')

In [23]:
a

inf

In [24]:
b

-inf

In [25]:
c

nan

Para probar la presencia de estos valores, use las funciones math.isinf () y math.isnan ()
ciones.   
Por ejemplo:

In [26]:
math.isfinite(a)

False

In [27]:
math.isinf(b)

True

In [28]:
math.isnan(c)

True

Para obtener información más detallada sobre estos valores especiales de punto flotante, debe consulte la especificación IEEE 754.   

Sin embargo, hay algunos detalles complicados que debe tener en cuenta.
de, especialmente relacionado con comparaciones y operadores.

Los valores infinitos se propagarán en los cálculos de manera matemática. Por ejemplo:

In [29]:
a = float('inf')
a + 45

inf

In [30]:
a * 10

inf

In [31]:
10 / a

0.0

In [32]:
# Sin embargo, ciertas operaciones no están definidas y 
# darán como resultado un resultado de NaN.
a/a

nan

In [33]:
b = float('-inf')
a + b

nan

In [34]:
c = float('nan')
c + 45

nan

In [35]:
c * 2

nan

In [36]:
c = float('nan')
d = float('nan')

In [37]:
c == d

False

In [38]:
c is d

False

Debido a esto, la única forma segura de probar un valor de NaN es usar math.isnan (), como
mostrado en esta receta.
A veces, los programadores quieren cambiar el comportamiento de Python para generar excepciones cuando las operaciones dan como resultado un resultado infinito o NaN. 


In [4]:
import numpy as np

np.seterr(all='ignore')  # Configura NumPy para lanzar excepciones en errores de punto flotante

x = np.array([1.0]) / 0.0  # Esto lanzará un FloatingPointError

In [8]:
import numpy as np

np.seterr(divide='ignore')  # Ignora los errores de división por cero

x = np.array([1.0, -1.0, 0.0])
y = np.array([0.0, 0.0, 0.0])

resultado = x / y  # Esto generará [inf, -inf, nan] en lugar de un error

print(resultado)

[ inf -inf  nan]


/tmp/ipykernel_21082/279693908.py:8: RuntimeWarning: invalid value encountered in divide
  resultado = x / y  # Esto generará [inf, -inf, nan] en lugar de un error


In [16]:
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return float('inf') if a > 0 else float('-inf') if a < 0 else float('nan')

print(safe_divide(1.0, 0.0))   # inf
print(safe_divide(-1.0, 0.0))  # -inf
print(safe_divide(0.0, 0.0))   # nan

inf
-inf
nan


In [15]:
res

NameError: name 'res' is not defined

# Calcular con fracciones

3.8

- Problema
        
        Has entrado en una máquina del tiempo y de repente te encuentras trabajando en la primaria.
        Problemas de nivel de tarea que involucran fracciones. O quizás esté escribiendo código para hacer cálculos con medidas realizadas en su carpintería.    
        
        
- Solución
        
        El módulo de fracciones se puede utilizar para realizar cálculos matemáticos que involucren fracciones.   
        
Por ejemplo:

In [17]:
from fractions import Fraction

In [18]:
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)

27/16


In [19]:
c = a * b

In [25]:
print(c)

35/64


In [20]:
c.numerator

35

In [21]:
c.denominator

64

In [22]:
float(c)

0.546875

In [26]:
x = 3.75

In [27]:
x.as_integer_ratio()

(15, 4)

In [28]:
y = Fraction(* x.as_integer_ratio())
y

Fraction(15, 4)

In [29]:
print(y)

15/4


El cálculo con fracciones no surge a menudo en la mayoría de los programas, pero hay situaciones donde podría tener sentido usarlos. Por ejemplo, permitir que un programa acepte unidades de la medición en fracciones y realizar cálculos con ellos en esa forma podría aliviar la necesidad de que un usuario realice conversiones manualmente a decimales o flotantes.

# Calcular con matrices numéricas grandes

3.9

- Problema
        
        Necesita realizar cálculos en grandes conjuntos de datos numéricos, como matrices o cuadrículas.  
        
- Solución
        
        Para cualquier cálculo pesado que involucre matrices, use la biblioteca NumPy. La característica principal de NumPy es que le da a Python un objeto de matriz que es mucho más eficiente y mejor adecuado para el cálculo matemático que una lista estándar de Python. Aquí hay un pequeño ejemplo ilustrando importantes diferencias de comportamiento entre listas y matrices NumPy:

In [30]:
# Python lists
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2 

[1, 2, 3, 4, 1, 2, 3, 4]

In [31]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [32]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [33]:
# Numpy arrays
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2

array([2, 4, 6, 8])

In [34]:
ax + 10

array([11, 12, 13, 14])

In [35]:
ax + ay

array([ 6,  8, 10, 12])

Como puede ver, las operaciones matemáticas básicas que involucran matrices se comportan de manera diferente.
Específicamente, las operaciones escalares (por ejemplo, ax * 2 o ax + 10) aplican la operación en un
base elemento por elemento. Además, realizar operaciones matemáticas cuando ambos
los operandos son matrices aplica la operación a todos los elementos y produce una nueva matriz.
El hecho de que las operaciones matemáticas se apliquen a todos los elementos simultáneamente lo hace muy
funciones fáciles y rápidas de calcular en una matriz completa. Por ejemplo, si quieres
calcular el valor de un polinomio:

In [36]:
def f(x):
    return 3*x**2 - 2*x + 7

In [37]:
f(ax)

array([ 8, 15, 28, 47])

NumPy proporciona una colección de "funciones universales" que también permiten la operación de matriz. Estos son reemplazos de funciones similares que normalmente se encuentran en el módulo matemático.  
Por ejemplo:

In [38]:
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [39]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

El uso de funciones universales puede ser cientos de veces más rápido que recorrer la matriz elementos uno a la vez y realizar cálculos usando funciones en el módulo matemático.  
Por lo tanto, debe preferir su uso siempre que sea posible.
Bajo las sábanas, las matrices NumPy se asignan de la misma manera que en C o Fortran.
Es decir, son regiones de memoria grandes y contiguas que constan de datos de tipos homogéneos. Debido a esto, es posible hacer arreglos mucho más grandes que cualquier otro
normalmente en una lista de Python.   
Por ejemplo, si desea hacer una cuadrícula bidimensional de 10,000 por 10,000 flotantes, no es un problema:

In [40]:
grid = np.zeros(shape=(10000,10000), dtype=float)

In [41]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
np.random.rand(100,100)

array([[0.14932356, 0.3445986 , 0.43288445, ..., 0.2926302 , 0.01842197,
        0.24323808],
       [0.56117815, 0.99273029, 0.81991843, ..., 0.057458  , 0.33253559,
        0.1515472 ],
       [0.23491826, 0.60285094, 0.13634735, ..., 0.38856602, 0.34847279,
        0.62509576],
       ...,
       [0.45525435, 0.23728387, 0.14743598, ..., 0.33713478, 0.54161021,
        0.40165189],
       [0.29744616, 0.17682162, 0.16993876, ..., 0.19876727, 0.30147902,
        0.76531427],
       [0.45093304, 0.88387014, 0.79641914, ..., 0.54821912, 0.71795138,
        0.37139433]])

Un aspecto extremadamente notable de NumPy es la forma en que extiende la lista de Python
funcionalidad de indexación, especialmente con multidimensionales

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [44]:
a[1]

array([5, 6, 7, 8])

In [45]:
a[0]

array([1, 2, 3, 4])

In [46]:
a[0:2][0]

array([1, 2, 3, 4])

In [47]:
a[:1,1]

array([2])

In [48]:
a[:2,:2]

array([[1, 2],
       [5, 6]])

In [49]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [50]:
# Broadcast un vector de fila a través de una operación en todas las filas
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 107, 109, 111],
       [109, 111, 113, 115]])

In [51]:
# Asignación condicional en una matriz
np.where(a < 10, a, float("nan"))

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., nan, nan, nan]])

NumPy es la base de una gran cantidad de bibliotecas de ciencia e ingeniería en
Pitón. También es uno de los módulos más grandes y complicados de uso generalizado.
Dicho esto, todavía es posible lograr cosas útiles con NumPy comenzando con
ejemplos simples y jugando. Una nota sobre el uso es que es relativamente común usar la instrucción import numpy
como np, como se muestra en la solución. Esto simplemente acorta el nombre a algo que es más
conveniente para escribir una y otra vez en su programa.
Para obtener más información, definitivamente debe visitar http://www.numpy.org.