# Realización de cálculos de álgebra lineal y matricial

3.10

- Problema
        
        Necesita realizar operaciones de álgebra matricial y lineal, como la multiplicación de matrices, encontrar determinantes, resolver ecuaciones lineales, etc.  
        
- Solución
        
        La biblioteca NumPy tiene un objeto de matriz que se puede utilizar para este propósito. Las matrices son algo similar a los objetos de arrays descritos en la receta 3.9, pero siguen el álgebra lineal

En NumPy, tanto los arrays como las matrices son estructuras de datos que se utilizan para almacenar y manipular datos numéricos, pero hay algunas diferencias clave entre ellos:

- Array (ndarray):

  - Definición: 
    - Un array de NumPy, o ndarray, es una colección de elementos del mismo tipo, que puede tener una o más dimensiones (1D, 2D, 3D, etc.).
  - Flexibilidad: 
    - Los arrays son más flexibles que las matrices. Puedes crear arrays de cualquier número de dimensiones y son la estructura de datos principal en NumPy.
  - Operaciones: 
    - Las operaciones en arrays se realizan elemento por elemento. Por ejemplo, si sumas dos arrays, se suman los elementos correspondientes.
  - Uso: 
    - Se utiliza generalmente para operaciones numéricas y científicas.


In [11]:
import numpy as np
   
array_1d = np.array([1, 2, 3])  # Array unidimensional
array_2d = np.array([[1, 2], [3, 4]])  # Array bidimensional

In [12]:
array_1d

array([1, 2, 3])

In [13]:
array_2d

array([[1, 2],
       [3, 4]])

- Matriz (matrix):

  - Definición: 
    - Una matriz en NumPy es un tipo específico de array que se utiliza principalmente para realizar operaciones de álgebra lineal. Se define como un objeto de la clase numpy.matrix.
  - Dimensiones: 
    - Las matrices son siempre bidimensionales (2D). No puedes crear matrices unidimensionales o tridimensionales.
  - Operaciones: 
    - Las operaciones entre matrices se realizan de manera diferente que en los arrays. Por ejemplo, la multiplicación entre matrices se realiza utilizando el producto matricial estándar (es decir, la multiplicación de matrices), mientras que en los arrays se realiza la multiplicación elemento a elemento.
  - Uso: 
    - Se utiliza principalmente en contextos de álgebra lineal.

In [1]:
import numpy as np

In [2]:
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])

In [3]:
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [4]:
# transpuesta
m.transpose()

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [5]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [ ]:
# inversa
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [7]:
# Crea un vector y multiplica
v = np.matrix([[2],[3],[4]])

In [8]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

In [9]:
V = np.array([[2],[3],[4]])

In [10]:
m * V

matrix([[ 8],
        [32],
        [ 2]])

Se pueden encontrar más operaciones en el subpaquete numpy.linalg.   
Por ejemplo:

In [19]:
# Determinante
np.linalg.det(m)

-229.99999999999983

In [21]:
# valores propios
np.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [25]:
# resuelve para x en  m*x = v
x = np.linalg.solve(m, v)
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [29]:
V = m * x
V

matrix([[2.],
        [3.],
        [4.]])

In [30]:
V == v

matrix([[ True],
        [ True],
        [ True]])

In [15]:
print(dir(np.linalg)) 

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'absolute_import', 'cholesky', 'cond', 'det', 'division', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'info', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'print_function', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


El álgebra lineal es obviamente un tema enorme que está mucho más allá del alcance de este cuaderno. 
Sin embargo, si necesita manipular matrices y vectores, NumPy es un buen comienzo.
Visite http://www.numpy.org para obtener información más detallada.

# Escoger cosas al azar

3.11

- Problema
        
        Desea seleccionar elementos aleatorios de una secuencia o generar números aleatorios.  
        
        
- Solución
        
        El módulo aleatorio tiene varias funciones para números aleatorios y selección aleatoria.
        Por ejemplo, para elegir un elemento aleatorio de una secuencia, use random.choice ():

In [31]:
import random

In [32]:
values = [1, 2, 3, 4, 5, 6]

In [34]:
random.choice(values)

1

Para tomar una muestra de N elementos donde los elementos seleccionados se eliminan de una consideración adicional , use random.sample () en su lugar:

In [35]:
random.sample(values,2)

[6, 4]

In [36]:
random.sample(values,2)

[1, 3]

In [37]:
random.sample(values,2)

[3, 5]

Si simplemente desea mezclar elementos en una secuencia en su lugar, use random.shuffle ():

In [38]:
random.shuffle(values)
values

[5, 2, 4, 3, 6, 1]

Para producir números enteros aleatorios, use random.randint ():

In [40]:
random.randint(0,10)

6

Para producir valores uniformes de punto flotante en el rango de 0 a 1, use random.random ():

In [41]:
random.random()

0.858635854304012

Para obtener N bits aleatorios expresados como un número entero, use random.getrandbits ():

In [42]:
random.getrandbits(200)

1532464694944846029507700144942093405934772136370017386786053

El módulo aleatorio calcula números aleatorios utilizando el algoritmo Mersenne Twister.
Este es un algoritmo determinista, pero puede alterar la semilla inicial usando el
función random.seed (). Por ejemplo:
```python
random.seed() # Semilla basada en la hora del sistema u os.urandom ()
random.seed(12345) # Semilla basada en el entero dado
random.seed(b'bytedata') # Semilla basada en datos de bytes
```

Además de la funcionalidad mostrada, random () incluye funciones para uniformes, Gaus‐
sian y otras distribuciones de probabilidad. Por ejemplo, random.uniform () calcula
números distribuidos uniformemente, y random.gauss () calcula distribuidos gauseana. Consulte la documentación para obtener información sobre otras distribuciones compatibles.
Las funciones en random () no deben usarse en programas relacionados con la criptografía. Si tu necesita dicha funcionalidad, considere usar funciones en el módulo ssl en su lugar. Por exemplo ssl.RAND_bytes () se puede usar para generar una secuencia criptográficamente segura de bytes aleatorios